name: "React client hackathon CI"
on: 
  push:
    branches: ["main"]
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.SSH_HOST}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.SSH_KEY}}
          host_fingerprint: ${{secrets.SSH_FINGERPRINT}}
          command: |
            cd ${{secrets.PROJECT_FOLDER}};
            git pull;
            docker compose down;
            docker compose build;
            docker compose up -d;
